### ISSUE TITLE
Loading doubles

### ISSUE THREAD

**Issue by A4AndreCRC** [seastan/dragncards-wotr-plugin#10]
When creating a new room, every line from the loading instructions in the LOG is repeated twice: the first time when a prebuilt deck is loaded using the pop-up menu, right after the room has been created, the second time when a player takes the first seat.
This does not create any issue with the gameplay, since there isn't any card that is actually loaded twice (it's not possible to check if shuffling happens twice), but it should not happen.

**Comment by seastan** [comment]
Thanks this was just a UI bug (did not effect gameplay) in the core dragncards code. The fix will go live next time the server restarts.
