### ISSUE TITLE
Repeated layout loading

### ISSUE THREAD

**Issue by A4AndreCRC** [seastan/dragncards-wotr-plugin#11]
When loading a new layout, or when changing the layout _**for everyone**_ from "onlyShowMyHand" to "allHandsVisible" and vice versa, every LOG and PROMPT is repeated about 7 times.
The gameplay is not affected, but the PROMPT triggered by the 6-players layout is quite annoying.

**Comment by A4AndreCRC** [comment]
Follow-up to this: I have edited and pushed the code so that the PROMPT is not repeated in 6 players. I reckon that when everyone changes the layout, every function is triggered by "every player", and that's why everything in the log (or any prompt with 'notifyAll') is repeated that amount of times.

**Comment by seastan** [comment]
This is an internal dragncards bug and will be fixed next time the server restarts
