### ISSUE TITLE
tableButtons and textBoxes level

### ISSUE THREAD

**Issue by A4AndreCRC** [seastan/dragncards-wotr-plugin#12]
The tableButtons and textBoxes should be moved to the background of the layout. When peeking at any deck, small parts of the visibility overlay are hidden behind those buttons. Examples attached. 

![immagine](https://github.com/user-attachments/assets/c5b95b05-5720-4efa-826c-ab6d10777c57)
![immagine](https://github.com/user-attachments/assets/589a8f5d-614f-4608-b338-238df9859357)

**Comment by seastan** [comment]
Internal DragnCards issue, will be resolved in the next update
